### ISSUE TITLE
HTML Solution

### ISSUE THREAD

**Issue by timdan2** [dtann80/ICS499_WordSearch#1]
HTML Solution shall show all the cells and the solution words shall be highlighted with the rectangles.

**Comment by timdan2** [comment]
This has been implemented in a separate demonstration tester, which needs to be integrated into the project code.

**Comment by timdan2** [comment]
Per Jasthi: Also, perfect drawing the rounded rectangles in the HTML.  Some words are only half-covered. Also, what happens if I Ctrl+ on the HTML to make the puzzle bigger.  All the rectangle arrangement is getting messed up.  See how that can be controlled with Ctrl + and Ctrl - options.

**Comment by timdan2** [comment]
Rectangle sizes are now good.  Created another card for the Ctrl +/- issue.

**Comment by wallgreeens** [comment]
Alright, so I'm working on getting the program to create an object using
the text file.  The current master program that was put up on github the
save feature doesn't seem to work anymore.  I get a null pointer error in
puzzle.java the when reading the  object langWordlList.  Is that still
where our words are stored.   I just thought I'd ask, otherwise I have the
day off tomorrow, so I'll have some time to figure it out.

**Comment by timdan2** [comment]
I'll look at it.
